Vector
DK318/first-term pull request #2
Opened 2020-07-03 15:34 UTC by DK318

2020-07-04 21:36 UTC, kt-cpp requested changes
Надо исправить большое число недостатков. Обратите внимание на использование `std::swap` и копирования.

Также очень хотелось бы, чтобы из PR были убраны файлы с заданием по ассемблеру.

2020-07-04 21:36 UTC, kt-cpp commented on vector/vector.h
> +T *vector<T>::erase(const_iterator pos) {
Кажется, что эта функций полная копипаста случая vector<T>::erase(iterator). Надо избавиться от этого.

2020-07-04 21:36 UTC, kt-cpp commented on vector/vector.h
> +    erase(end() - 1);
1. Не очень понятно, почему здесь нельзя явно руками удалить последний элемент.
2. **pop_back** должен быть **nothrow**. Понятно, что в данном случае это именно так, но всё равно очень некрасиво вызывать **erase**, который **weak**.

2020-07-04 21:36 UTC, kt-cpp commented on vector/vector.h
> +    data_[size_ - 1].~T();
Лучше сделать так, чтобы тут вызывался **pop_back**.

2020-07-04 21:36 UTC, kt-cpp commented on vector/vector.h
> +    insert(end(), val);
Аналогичная с **erase** ситуация.

2020-07-04 21:36 UTC, kt-cpp commented on vector/vector.h
> +    T value = val;
Зачем здесь выполняется копирование?

2020-07-04 21:36 UTC, kt-cpp commented on vector/vector.h
> +    if (size_ >= capacity_) {
Интересно, когда `size` может быть больше `capacity`?

2020-07-04 21:36 UTC, kt-cpp commented on vector/vector.h
> +T *vector<T>::insert(const_iterator pos, T const &val) {
Очень похоже на копипасту.

2020-07-04 21:36 UTC, kt-cpp commented on vector/vector.h
> +    while (position < max_pos) {
Мне не очень нравится выполняемый тут код.
1. Кажется, что тут переусложнен код. Почему надо разбирать отдельные случаи? Почему нельзя сделать просто `push_back`, а затем `swap` элементов с конца?
2. Вы выполняете копирование элементов в цикле. Гораздо более эффективно было бы делать `swap` элементов. Представьте, что происходит в случае `vector<vector<int>>`.

2020-07-04 21:36 UTC, kt-cpp commented on vector/vector.h
> +    size_t d = last - first;
Давайте будем давать переменным более осмысленные названия, чем `d`.

2020-07-04 21:36 UTC, kt-cpp commented on vector/vector.h
> +        data_[i] = data_[i + d];
Надо избавиться от копирования. Мотивация аналогична `insert`.

2020-07-04 21:36 UTC, kt-cpp commented on vector/vector.h
> +T *vector<T>::erase(const_iterator first, const_iterator last) {
Опять копипаста

2020-07-06 15:25 UTC, kt-cpp commented
Будешь резолвить и дальше, получишь - автоматом

2020-07-06 15:29 UTC, kt-cpp commented on vector/vector.h
> +T *vector<T>::erase(const_iterator pos) {
Предыдущий проверяющий ошибся, нужно оставить const_iterator варианты, а iterator выкинуть)

2020-07-06 15:34 UTC, kt-cpp commented on vector/vector.h
> +T *vector<T>::erase(const_iterator pos) {
[minor]

2020-07-06 17:01 UTC, DK318 commented
Понял, извиняюсь. Что нужно сделать, чтобы + получить?

2020-07-07 12:10 UTC, kt-cpp commented
Поправь последний минор

2020-07-07 17:46 UTC, merged