Added bigint-opt hw
DK318/first-term pull request #4
Opened 2020-07-06 03:45 UTC by DK318

2020-07-07 12:31 UTC, kt-cpp requested changes
Глобальные проблемы с архитектурой, так что код детально не смотрелся:
* Нужно хранить не один элемент, а массив, размер которого можно менять, не нарушая логики всего кода, одно строчкой
* Ни в одной из правильных реализаций не нужен флаг `is_empty`
А ещё хочется вынести больше COW логики в соответствующий класс с помощью статических и не очень функций таких как, например, `release, add_ref` и не только

2020-07-08 10:26 UTC, kt-cpp requested changes

2020-07-08 10:26 UTC, kt-cpp commented on bigint-optimized/shared_pointer.cpp
> +shared_pointer *shared_pointer::release()
[note] Название не очень соответствует поведению

2020-07-08 10:26 UTC, kt-cpp commented on bigint-optimized/optimized_container.cpp
> +    if (*this == other) {
[minot] Равенство через оператор не говорит о том, что это один и тот же объект в памяти. А именно это тебя тут интересует

2020-07-08 12:19 UTC, DK318 commented on bigint-optimized/shared_pointer.cpp
> +shared_pointer *shared_pointer::release()
fixed

2020-07-08 12:19 UTC, DK318 commented on bigint-optimized/optimized_container.cpp
> +    if (*this == other) {
fixed

2020-09-17 19:15 UTC, kt-cpp approved these changes

2020-09-17 19:15 UTC, merged